# FSR Autogenerated Content. DO NOT DELETE
from .radware_alteon_wrapper_ipAclNewCfgTable import *

supported_operations = {
    'view_table': view_table, 
    'view_table_element': view_table_element, 
    'edit_table_element': edit_table_element,
    'add_table_element': add_table_element, 
    'delete_table_element': delete_table_element
}
